// This file is generated by Slice Machine. Update with care!

import AreaDeAtuacao from './AreaDeAtuacao';
import FullBannerHome from './FullBannerHome';
import Integrante from './Integrante';
import QuemSomos from './QuemSomos';
import QuemSomosHome from './QuemSomosHome';

export {
	AreaDeAtuacao,
	FullBannerHome,
	Integrante,
	QuemSomos,
	QuemSomosHome,
};

export const components = {
	area_de_atuacao: AreaDeAtuacao,
	full_banner_home: FullBannerHome,
	integrante: Integrante,
	quem_somos: QuemSomos,
	quem_somos_home: QuemSomosHome,
};
