// This file is generated by Slice Machine. Update with care!

import FullBannerHome from './FullBannerHome';
import QuemSomosHome from './QuemSomosHome';

export {
	FullBannerHome,
	QuemSomosHome,
};

export const components = {
	full_banner_home: FullBannerHome,
	quem_somos_home: QuemSomosHome,
};
