// Code generated by Slice Machine. DO NOT EDIT.

import AreaDeAtuacao from './AreaDeAtuacao';
import AreasDeAtuacaoHome from './AreasDeAtuacaoHome';
import ArtigoConteudo from './ArtigoConteudo';
import FullBannerHome from './FullBannerHome';
import Integrante from './Integrante';
import QuemSomos from './QuemSomos';
import QuemSomosHome from './QuemSomosHome';

export {
	AreaDeAtuacao,
	AreasDeAtuacaoHome,
	ArtigoConteudo,
	FullBannerHome,
	Integrante,
	QuemSomos,
	QuemSomosHome,
};

export const components = {
	area_de_atuacao: AreaDeAtuacao,
	areas_de_atuacao_home: AreasDeAtuacaoHome,
	artigo_conteudo: ArtigoConteudo,
	full_banner_home: FullBannerHome,
	integrante: Integrante,
	quem_somos: QuemSomos,
	quem_somos_home: QuemSomosHome,
};
